### ISSUE TITLE
Naming nit

### ISSUE THREAD

**Issue by chocolateboy** [sinonjs/referee#208]
> Symmetric assert/refute (refute is referee's "assert.not*")

:thinking: "assert" and "refute" aren't "symmetrical"...

"**Refute**" (*demonstrate* that something is false) isn't the opposite of "**assert**" (*state* that something is true). It's the opposite of "**prove**" (*demonstrate* that something is true). The opposite of "assert" is "**deny**" (*state* that something is false).

I guess it's too late to change it, but perhaps it could be added as an alias?

(I realise the name comes from minitest, and the noun ("refutations") sounds like a better complement to "assertions" (to me) than "denials".)

**Comment by mantoni** [comment]
I would rather change it in the documentation than changing it in the code. Like the explanation sais, refute is referee's "assert.not", which describes the semantics how this is applied. The word "symmetric" was chosen to explain that every `assert.*` function has a corresponding `refute.*`  function. Do you have an idea how we can improve the description?

 I also agree that "refute" sounds better than "deny", especially in the context of a "referee" :)

**Comment by chocolateboy** [comment]
> Do you have an idea how we can improve the description?

Serves me right for nitpicking: now I have to do the [hardest thing](https://martinfowler.com/bliki/TwoHardThings.html) in computer science and try to think of a better wording :-)

How about:

> Complementary `assert`/`refute` (refute is **referee**'s `assert.not`)

Or:

> `refute` as the inverse of `assert` (rather than `assert.not`)

Or:

> `refute` to negate `assert` (rather than `assert.not`)

**Comment by mantoni** [comment]
I like “Complementary assert/refute (refute is referee's assert.not)” 👍.

@mroderick What do you think?

**Comment by mroderick** [comment]
I like "complementary" 👍
