### ISSUE TITLE
Allow assert.rejects to take only one argument

### ISSUE THREAD

**Issue by BryanDonovan** [sinonjs/referee#219]
The `assert.rejects` function currently requires a second argument, which much be `identical` to what the target function rejected with.  This can be difficult to determine in many cases.  It would be great if the second argument was optional (for what it's worth, the docs say the second param is optional here, but maybe these aren't up to date: https://sinonjs.github.io/referee/#rejects).  Here's an example (using mocha) of how I'd like this to work:

```javascript
const {assert} = require('@sinonjs/referee');

async function thrower() {
    throw new Error('foo');
}

describe("assert.reject", () => {
    it("does not require a second argument", async () => {
        await assert.rejects(thrower());
    });
});
```

Or perhaps it could follow the same api as `assert.match()`.  Then I could do something like: 
```javascript
await assert.rejects(thrower(), /foo/);
```

**Comment by mantoni** [comment]
Yes, I agree that the second argument should be optional, as stated in the docs. This is a bug.

Would you care to send a PR with a fix?

**Comment by mantoni** [comment]
Regarding matchers, I think you can already pass something like `match(/foo/)` as the second argument.

**Comment by BryanDonovan** [comment]
I'd love to do a PR, but my company requires me to get legal approval, etc., which would take a while.  Regarding the matcher, I can't seem to get it to work.  Do you have an example?

**Comment by mantoni** [comment]
This should work:

```js
const { assert, match } = require('@sinonjs/referee');

await assert.rejects(Promise.reject('nope'), match.string);
```
