### ISSUE TITLE
Feature: assert.resolves and assert.rejects

### ISSUE THREAD

**Issue by mroderick** [sinonjs/referee#27]
I was doing some work with async functions, and was finding myself having to write something like this to verify the error handling.

```js
try {
    await myAsyncFunction();
} catch (e) {
    error = e;
} finally {
    assert(error instanceof TypeError);
    assert.equals(
        error.message,
        'Oops'
    );
}
```

This seems clumsy, compared to a lot of the things we can do with `referee`.

I'd prefer to write something like this: 

```js
// option 1: expand assert.exception to cover promises
assert.exception(myAsyncFunction(), {name: 'TypeError', message: 'Oops'})

// option 2: adding extra methods 
assert.rejects(myAsyncFunction(), {name: 'TypeError', message: 'Oops'});
```

Considering that we have `sinon.fake.resolves()` and `sinon.fake.rejects()`, I think I'd prefer option 2 and add `assert.resolves()` and `assert.rejects()`.

I imagine that `assert.rejects` follows the API established with `assert.exception`, except for the fact that it understands promises.

**Comment by mroderick** [comment]
@mantoni I know you've picked up `referee` again, have you run into situations where you'd like to test rejected promises and thought this was unnecessarily complex?

**Comment by mantoni** [comment]
No, I avoid using promises. I think they’re a complicated and error-prone abstraction that only makes sense to me in the context of async / await.

**Comment by mroderick** [comment]
When you use `async/await`, you're still using promises. How do you write tests for code that you expect to throw?

**Comment by mantoni** [comment]
I’m not using async / await yet. So I have no experience testing code with promises.

**Comment by mroderick** [comment]
If this is supposed to work with Promises, it should return a `Promise`, or the test runner won't know what to do with it.

```js
// in Mocha you could do
it('should reject with "Oops"', function(){
    return assert.rejects(myAsyncFunction(), {name: 'TypeError', message: 'Oops'});
});

// or with async/await
it('should reject with "Oops"', async function(){
    await assert.rejects(myAsyncFunction(), {name: 'TypeError', message: 'Oops'});
});
```

Would it be too confusing that we have methods that returns promises, is what I wonder?

**Comment by mgred** [comment]
Approached this in #44. If this is still relevant, let's discuss this further :smile:
