### ISSUE TITLE
Edge case: isBoolean vs. new Boolean()

### ISSUE THREAD

**Issue by mroderick** [sinonjs/referee#65]
Passing a Boolean object, created using `new Boolean()` to `assert.isBoolean()` does not pass.

**What did you expect to happen?**

I imagine that the `assert.isBoolean` would pass, and that `refute.isBoolean` would fail.

I do think that creating Boolean values using `new` should be avoided, but it's part of the language, so we should probably handle it well.

See https://eslint.org/docs/rules/no-new-wrappers

**What actually happens**

`assert.isBoolean` fails, and `refute.isBoolean` passes

**How to reproduce**

```js
var referee = require("referee");
var b = new Boolean(true);

// passes
referee.refute.isBoolean(b);

// fails
referee.assert.isBoolean(b);
```

**Comment by mantoni** [comment]
It‘s part of the language that `new Boolean()` is an object, not a boolean primitive. I‘d argue that `isBoolean` should check for the primitive only and that I‘d consider it a bug in my code if I accidentally created a Boolean prototype instance. I wouldn‘t like the behavior to change in this case.

Having said that, we could support this with an additional API.

**Comment by mantoni** [comment]
Some background on ECMA internals regarding this: The reason for the existence of `Boolean`, `Number`, `String` etc is that primitives can‘t have functions. So if you write `“test“.toUpperCase()`, the engine creates a primitive string `“Test“`, converts it to a `String` prototype on the dot operator, finds the `toUpperCase` function in the prototype chain and calls it using the new String instance as `this`. The `toUpperCase` function in turn returns a primitive string.

So primitives and their object wrappers are different types, but newing them up should actually throw in my opinion. It’s really just going to cause trouble. This mistake was not repeated with newer language APIs. For example, `new Symbol()` throws a `TypeError`.
