### ISSUE TITLE
Suggestion: Move DOM related assertions into separate module

### ISSUE THREAD

**Issue by mantoni** [sinonjs/referee#90]
When I'm testing the DOM, I'd like to have more assertions, for `name`, `value`, `checked` etc. Referee is also used on Node and I find it a bit messy to have DOM related checks in core.

We have the possibility to create sets of custom assertions. I would like to create a new repository for them and move the functionality there.

**Comment by mroderick** [comment]
I've been having similar thoughts. I'd love to have a wider set of assertions, and don't feel they all belong in core.

A few questions spring to mind:

* Is there anything that warns the user about name collisions when trying to add an assertion that already exists?
* If there is, do we have a recommendation for how to solve it?

Considering the very small adoption of `referee`, it's probably premature to implement any solutions to these questions just yet. 

How shall we name the package?

* `@sinonjs/referee-assert-dom`
* `@sinonjs/referee-extra-dom`
* `@sinonjs/referee-dom`

**Comment by mantoni** [comment]
Oh, I havn't thought about this. I guess adding a simple check when registering assertions is a good idea.

I like `@sinonjs/referee-dom` best.

**Comment by mroderick** [comment]
I say run with it!

(I'll try to get the refactoring of the tests in this repository done this month)

**Comment by mgred** [comment]
Totally like that idea. Keeping a slim core and providing extras in other packages sounds good to me.
+1 `@sinonjs/referee-dom`

**Comment by mroderick** [comment]
I've set up a repository for this: https://github.com/sinonjs/referee-plugin-dom

**Comment by mantoni** [comment]
👍👍
